"""AWS Lambda Function URL adapter for the short-lived external MCP demo.

The bearer token is fetched from one SSM SecureString at cold start.  This
module intentionally does not log Lambda events, request bodies, or headers.
"""

from __future__ import annotations

import os
from typing import Any

from mangum import Mangum
from mcp.server.transport_security import TransportSecuritySettings

from .server import DEFAULT_MAX_REQUEST_BODY_BYTES, create_app


def load_bearer_token(parameter_name: str, *, ssm_client: Any | None = None) -> str:
    """Read one configured SecureString without exposing its value in errors."""
    if not parameter_name:
        raise RuntimeError("MCP_AUTH_TOKEN_PARAMETER must name the demo SecureString.")
    if ssm_client is None:
        import boto3

        ssm_client = boto3.client("ssm")
    value = ssm_client.get_parameter(Name=parameter_name, WithDecryption=True).get("Parameter", {}).get("Value")
    if not isinstance(value, str) or not value:
        raise RuntimeError("The configured demo token parameter is missing or empty.")
    return value


def _allowed_origins_from_environment() -> tuple[str, ...]:
    value = os.environ.get("MCP_ALLOWED_ORIGINS", "")
    return tuple(origin.strip() for origin in value.split(",") if origin.strip())


def _max_request_body_bytes_from_environment() -> int:
    raw_value = os.environ.get("MCP_MAX_REQUEST_BODY_BYTES", str(DEFAULT_MAX_REQUEST_BODY_BYTES))
    try:
        value = int(raw_value)
    except ValueError as error:
        raise RuntimeError("MCP_MAX_REQUEST_BODY_BYTES must be an integer.") from error
    if value < 1:
        raise RuntimeError("MCP_MAX_REQUEST_BODY_BYTES must be positive.")
    return value


_bearer_token: str | None = None


def _cached_bearer_token() -> str:
    """Load the SecureString once per warm execution environment."""
    global _bearer_token
    if _bearer_token is None:
        _bearer_token = load_bearer_token(os.environ.get("MCP_AUTH_TOKEN_PARAMETER", ""))
    return _bearer_token


def create_lambda_app() -> Any:
    """Create a fresh stateless ASGI app using the warm token cache.

    Function URL host names are generated by AWS after the function is created,
    so the SDK's static Host allowlist cannot be supplied at template time.
    Origin allowlisting and bearer authentication remain enforced by the outer
    protocol middleware.
    """
    return create_app(
        auth_token=_cached_bearer_token(),
        allowed_origins=_allowed_origins_from_environment(),
        max_request_body_bytes=_max_request_body_bytes_from_environment(),
        transport_security=TransportSecuritySettings(enable_dns_rebinding_protection=False),
    )


def handler(event: dict[str, Any], context: Any) -> dict[str, Any]:
    """Lambda handler with a fresh MCP lifespan for each stateless request.

    MCPServer's ASGI session manager opens and closes with the app lifespan.
    Reusing one adapter after that close would leave its task group unavailable,
    so this function creates a fresh adapter per invocation while retaining the
    already-authorized token only in the warm execution environment.
    """
    return Mangum(create_lambda_app(), lifespan="auto")(event, context)
